### ISSUE TITLE
reporte de la practica de hilos 

### ISSUE THREAD

**Issue by MLR062998** [SistemasTecTlaxiaco/practica-de-hilos-MLR062998#2]
[Practica de hilos_T2.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-MLR062998/files/6513157/Practica.de.hilos_T2.pdf)

**Comment by Azucena-Tejeda** [comment]
calificación 19

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
